name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: See the code :D
        uses: actions/checkout@v4.2.1

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images :D
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: .
          push: true
          tags: |
            luan4343543/repository-docker-hub-test:v1
            luan4343543/repository-docker-hub-test:latest
    
